const menuButton=document.querySelector("[data-menu-button]"),nav=document.querySelector("[data-nav]");if(menuButton&&nav){menuButton.addEventListener("click",()=>{const open=nav.classList.toggle("open");menuButton.setAttribute("aria-expanded",String(open))});nav.querySelectorAll("a").forEach(a=>a.addEventListener("click",()=>{nav.classList.remove("open");menuButton.setAttribute("aria-expanded","false")}))}const reveal=()=>document.querySelectorAll(".reveal").forEach(el=>el.classList.add("visible"));if("IntersectionObserver"in window){const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add("visible");observer.unobserve(entry.target)}}),{threshold:.12});document.querySelectorAll(".reveal").forEach(el=>observer.observe(el))}else reveal();

const FC_API_URL="https://ialobcshxbesmncngixx.supabase.co";
const FC_PUBLIC_KEY="sb_publishable_5fmGpjGAQm7qwUS1xtp-zg_CI4fenzN";
async function fcRpc(name,body={}){
 const r=await fetch(FC_API_URL+"/rest/v1/rpc/"+name,{method:"POST",headers:{"Content-Type":"application/json","apikey":FC_PUBLIC_KEY},body:JSON.stringify(body)});
 if(!r.ok)throw new Error("Marketplace request failed");
 return r.status===204?null:r.json();
}
async function loadPublicMarketplace(){
 const grid=document.querySelector("#public-market-grid");if(!grid)return;
 const esc=v=>String(v??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]));
 try{
  const rows=await fcRpc("fc_public_marketplace");
  if(!rows?.length){grid.innerHTML='<div class="market-empty"><strong>No products published yet.</strong><p>Approved Farmers Connect listings will automatically appear here.</p></div>';return}
  grid.innerHTML=rows.map(r=>'<article class="market-card"><div class="market-visual">'+(r.image_url?'<img src="'+esc(r.image_url)+'" alt="'+esc(r.product_name)+'">':'<div class="market-placeholder"><span>Ecofarms Marketplace</span><strong>'+esc(r.product_name)+'</strong></div>')+'<span class="market-badge">'+esc(r.verification_badge||"Verified supply")+'</span></div><div class="market-content"><div class="market-meta"><span>'+esc(r.category||"Fresh produce")+'</span><span>'+(r.availability_type==="upcoming_harvest"?"Upcoming harvest":"Available now")+'</span></div><h3>'+esc(r.product_name)+'</h3><p>'+esc(r.variety||r.description||"Quality agricultural supply")+'</p><div class="market-price"><strong>'+(r.unit_price!=null?esc(r.currency)+" "+esc(r.unit_price):"Price on request")+'</strong><span>per '+esc(r.quantity_unit)+'</span></div><div class="market-stock">'+esc(r.available_quantity)+' '+esc(r.quantity_unit)+' available</div><small>'+esc(r.seller_name)+(r.location?' · '+esc(r.location):'')+'</small><button type="button" class="button gold" data-market-view="'+esc(r.id)+'">View product</button></div></article>').join("");
  grid.querySelectorAll("[data-market-view]").forEach(b=>b.addEventListener("click",async()=>{const card=b.closest(".market-card"),id=b.dataset.marketView;fcRpc("fc_track_listing_view",{p_listing_id:id}).catch(()=>{});const row=rows.find(x=>String(x.id)===String(id));if(!row)return;b.textContent="Product details";b.disabled=false;const existing=card.querySelector(".market-details");if(existing){existing.remove();b.textContent="View product";return}const d=document.createElement("div");d.className="market-details";d.innerHTML='<p><strong>Product details</strong></p><p>'+esc(row.description||row.variety||"Verified agricultural supply available through Ecofarms Marketplace.")+'</p><p><b>Supply:</b> '+esc(row.available_quantity)+' '+esc(row.quantity_unit)+' · <b>Location:</b> '+esc(row.location||"Contact seller")+'</p><form class="market-inquiry"><input name="name" required placeholder="Your name"><input name="phone" required placeholder="Phone / WhatsApp"><input name="email" type="email" placeholder="Email (optional)"><input name="quantity" required type="number" min="0.01" step="0.01" max="'+esc(row.available_quantity)+'" placeholder="Quantity ('+esc(row.quantity_unit)+')"><select name="fulfillment"><option value="delivery">Delivery</option><option value="pickup">Pickup</option></select><input name="location" placeholder="Delivery location"><button class="button gold" type="submit">Request to buy / reserve</button><p class="inquiry-status"></p></form>';card.querySelector(".market-content").appendChild(d);d.querySelector("form").addEventListener("submit",async e=>{e.preventDefault();const form=e.currentTarget,status=form.querySelector(".inquiry-status"),fd=new FormData(form),btn=form.querySelector("button");btn.disabled=true;status.textContent="Sending request…";try{const code=await fcRpc("fc_submit_marketplace_inquiry_receipt",{p_listing_id:id,p_name:fd.get("name"),p_phone:fd.get("phone"),p_email:fd.get("email")||"",p_quantity:Number(fd.get("quantity")),p_fulfillment:fd.get("fulfillment"),p_location:fd.get("location")||""});status.innerHTML="Request received. Your tracking reference is <strong>"+esc(code)+"</strong>. Keep this reference to track your order.";form.reset()}catch(err){status.textContent="We could not send the request. Please try again."}finally{btn.disabled=false}})}));
 }catch{grid.innerHTML='<div class="market-empty"><strong>Marketplace temporarily unavailable.</strong><p>Please try again shortly.</p></div>'}
}
loadPublicMarketplace();

const trackForm=document.querySelector("#track-order-form"),trackResult=document.querySelector("#track-order-result");
if(trackForm&&trackResult)trackForm.addEventListener("submit",async e=>{e.preventDefault();const fd=new FormData(trackForm);trackResult.innerHTML="<p>Checking your order…</p>";try{const rows=await fcRpc("fc_track_public_order",{p_tracking_code:fd.get("code"),p_contact:fd.get("contact")});if(!rows?.length){trackResult.innerHTML="<div class='market-empty'><strong>Order not found.</strong><p>Check the reference and use the same phone number or email used for the request.</p></div>";return}const r=rows[0],status=r.order_status||r.inquiry_status||"submitted",steps=["submitted","reserved","preparing","dispatched","delivered","completed"],labels=["Request submitted","Accepted / reserved","Preparing","Dispatched","Delivered","Completed"],current=status==="accepted"?1:Math.max(0,steps.indexOf(status));trackResult.innerHTML="<article class='tracking-card'><div><span class='market-badge'>"+esc(r.tracking_code)+"</span><h3>"+esc(r.product_name)+"</h3><p>"+esc(r.quantity)+" "+esc(r.quantity_unit)+" · "+(r.unit_price!=null?esc(r.currency)+" "+esc(r.total_amount):"Price pending")+"</p><small>"+esc(r.seller_name)+" · "+esc(r.fulfillment_preference)+(r.delivery_location?" · "+esc(r.delivery_location):"")+"</small></div><div class='tracking-steps'>"+labels.map((x,i)=>"<span class='"+(i<=current?"done":"")+"'><b>"+(i+1)+"</b>"+x+"</span>").join("")+"</div></article>"}catch{trackResult.innerHTML="<div class='market-empty'><strong>Tracking is temporarily unavailable.</strong><p>Please try again shortly.</p></div>"}});
