const menuButton=document.querySelector("[data-menu-button]"),nav=document.querySelector("[data-nav]");if(menuButton&&nav){menuButton.addEventListener("click",()=>{const open=nav.classList.toggle("open");menuButton.setAttribute("aria-expanded",String(open))});nav.querySelectorAll("a").forEach(a=>a.addEventListener("click",()=>{nav.classList.remove("open");menuButton.setAttribute("aria-expanded","false")}))}const reveal=()=>document.querySelectorAll(".reveal").forEach(el=>el.classList.add("visible"));if("IntersectionObserver"in window){const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add("visible");observer.unobserve(entry.target)}}),{threshold:.12});document.querySelectorAll(".reveal").forEach(el=>observer.observe(el))}else reveal();

const FC_API_URL="https://ialobcshxbesmncngixx.supabase.co";
const FC_PUBLIC_KEY="sb_publishable_5fmGpjGAQm7qwUS1xtp-zg_CI4fenzN";
async function fcRpc(name,body={}){
 const r=await fetch(FC_API_URL+"/rest/v1/rpc/"+name,{method:"POST",headers:{"Content-Type":"application/json","apikey":FC_PUBLIC_KEY},body:JSON.stringify(body)});
 if(!r.ok)throw new Error("Marketplace request failed");
 return r.status===204?null:r.json();
}
async function loadPublicMarketplace(){
 const grid=document.querySelector("#public-market-grid");if(!grid)return;
 const esc=v=>String(v??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]));
 try{
  const rows=await fcRpc("fc_public_marketplace");
  if(!rows?.length){grid.innerHTML='<div class="market-empty"><strong>No products published yet.</strong><p>Approved Farmers Connect listings will automatically appear here.</p></div>';return}
  grid.innerHTML=rows.map(r=>'<article class="market-card"><div class="market-visual">'+(r.image_url?'<img src="'+esc(r.image_url)+'" alt="'+esc(r.product_name)+'">':'<div class="market-placeholder"><span>Ecofarms Marketplace</span><strong>'+esc(r.product_name)+'</strong></div>')+'<span class="market-badge">'+esc(r.verification_badge||"Verified supply")+'</span></div><div class="market-content"><div class="market-meta"><span>'+esc(r.category||"Fresh produce")+'</span><span>'+(r.availability_type==="upcoming_harvest"?"Upcoming harvest":"Available now")+'</span></div><h3>'+esc(r.product_name)+'</h3><p>'+esc(r.variety||r.description||"Quality agricultural supply")+'</p><div class="market-price"><strong>'+(r.unit_price!=null?esc(r.currency)+" "+esc(r.unit_price):"Price on request")+'</strong><span>per '+esc(r.quantity_unit)+'</span></div><div class="market-stock">'+esc(r.available_quantity)+' '+esc(r.quantity_unit)+' available</div><small>'+esc(r.seller_name)+(r.location?' · '+esc(r.location):'')+'</small><button type="button" class="button gold" data-market-view="'+esc(r.id)+'">View product</button></div></article>').join("");
  grid.querySelectorAll("[data-market-view]").forEach(b=>b.addEventListener("click",async()=>{const card=b.closest(".market-card"),id=b.dataset.marketView;fcRpc("fc_track_listing_view",{p_listing_id:id}).catch(()=>{});const row=rows.find(x=>String(x.id)===String(id));if(!row)return;b.textContent="Product details";b.disabled=false;const existing=card.querySelector(".market-details");if(existing){existing.remove();b.textContent="View product";return}const d=document.createElement("div");d.className="market-details";d.innerHTML='<p><strong>Product details</strong></p><p>'+(esc(row.description||row.variety||"Verified agricultural supply available through Ecofarms Marketplace."))+'</p><p><b>Supply:</b> '+esc(row.available_quantity)+' '+esc(row.quantity_unit)+' · <b>Location:</b> '+esc(row.location||"Contact seller")+'</p><p class="market-note">Ordering and reservation controls are being connected to Farmers Connect.</p>';card.querySelector(".market-content").appendChild(d)}));
 }catch{grid.innerHTML='<div class="market-empty"><strong>Marketplace temporarily unavailable.</strong><p>Please try again shortly.</p></div>'}
}
loadPublicMarketplace();
